name: weight_tracker
description: A Weight Tracking app developed with Flutter.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.16.1
  sqflite: ^1.3.0
  path_provider: ^1.6.9
  provider: ^4.0.5
  bloc: ^6.0.1
  flutter_bloc: ^6.0.1
  equatable: ^1.1.1
  shared_preferences: ^0.5.6+3

  cupertino_icons: ^0.1.2
  google_fonts: ^0.4.0
  fl_chart: ^0.9.0
  flutter_calendar_carousel: ^1.4.11
  flutter_vector_icons: ^0.2.1
  animated_text_kit: ^2.2.0
  flutter_spinkit: ^4.1.2+1
  flutter_page_transition: ^0.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
